"""Watermark domain analyzer for AI-generated audio detection.

Checks:
1. AudioSeal watermark detection (Meta AI)

Watermark detection is the only "100% positive" proof of AI generation.
Requires the `audioseal` library (optional dependency).
"""

import logging
from typing import Optional

import numpy as np

from .base import AnalysisDepth, ArtifactResult, BaseAnalyzer, DomainResult

logger = logging.getLogger(__name__)

# Optional imports
HAS_AUDIOSEAL = False
HAS_TORCH = False

try:
    import torch
    HAS_TORCH = True
except ImportError:
    pass

try:
    from audioseal import AudioSeal
    HAS_AUDIOSEAL = True
except ImportError:
    logger.info("audioseal not installed — watermark detection disabled. "
                "Install with: uv pip install audioseal")


class WatermarkAnalyzer(BaseAnalyzer):
    """Detects AI watermarks embedded in generated audio."""

    domain = "watermark"
    display_name = "Watermark Detection"
    base_weight = 0.10
    min_depth = AnalysisDepth.DEEP

    def analyze(
        self,
        y_mono: np.ndarray,
        sr: int,
        y_stereo: Optional[np.ndarray] = None,
        depth: AnalysisDepth = AnalysisDepth.STANDARD,
    ) -> DomainResult:
        if not HAS_AUDIOSEAL or not HAS_TORCH:
            missing = []
            if not HAS_TORCH:
                missing.append("torch")
            if not HAS_AUDIOSEAL:
                missing.append("audioseal")
            return self._inactive_result(
                f"Watermark detection requires: {', '.join(missing)}. "
                "Install with: uv pip install audioseal"
            )

        artifacts = []
        try:
            artifacts.append(self._check_audioseal(y_mono, sr))
        except Exception as e:
            logger.warning("AudioSeal watermark check failed: %s", e)

        return self._make_domain_result(artifacts)

    def _check_audioseal(self, y: np.ndarray, sr: int) -> ArtifactResult:
        """Detect AudioSeal watermark from Meta AI.

        AudioSeal uses a generator-detector architecture for localized
        watermark detection. If detected, this is near-definitive proof
        of AI generation.
        """
        import torch
        import librosa

        # AudioSeal expects 16kHz input
        target_sr = 16000
        if sr != target_sr:
            y_resampled = librosa.resample(y, orig_sr=sr, target_sr=target_sr)
        else:
            y_resampled = y

        # Convert to torch tensor: (batch, channels, samples)
        audio_tensor = torch.tensor(
            y_resampled, dtype=torch.float32
        ).unsqueeze(0).unsqueeze(0)

        # Load detector model
        detector = AudioSeal.load_detector("audioseal_detector_16bits")

        # Run detection
        with torch.no_grad():
            result, message = detector.detect_watermark(audio_tensor, sample_rate=target_sr)

        # result is a probability tensor
        confidence = float(result.mean().item()) if result is not None else 0.0

        if confidence > 0.8:
            probability = 0.99
            severity = "high"
        elif confidence > 0.5:
            probability = 0.7
            severity = "medium"
        elif confidence > 0.3:
            probability = 0.3
            severity = "low"
        else:
            probability = 0.0
            severity = "none"

        detected = confidence > 0.5

        return ArtifactResult(
            name="audioseal_watermark",
            detected=detected,
            severity=severity,
            value=round(confidence, 3),
            description=(
                f"AudioSeal watermark confidence: {confidence:.3f}. "
                + (
                    "AI watermark detected — this is near-definitive proof "
                    "that the audio was generated by an AI model with watermarking enabled."
                    if detected
                    else "No AI watermark detected (note: not all AI models embed watermarks)."
                )
            ),
            probability=probability,
            weight=1.0,  # Overridden by centralized weights.py
        )
